DWAPlannerROS:
  # Robot Configuration Parameters
  max_vel_x: 1.5
  min_vel_x: 0.0
  max_vel_y: 0.0  # 0 for a differential-drive robot
  min_vel_y: 0.0  
  max_trans_vel: 1.5
  min_trans_vel: 0.1
  max_rot_vel: 3.8
  min_rot_vel: 0.0
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2

  # Goal Tolerance
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2

  # Trajectory Scoring Parameters
  sim_time: 1.7
  vx_samples: 20
  vy_samples: 10
  vth_samples: 20
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01

  # Obstacle Avoidance
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

