# teb_local_planner_params.yaml

 TebLocalPlannerROS:
   max_vel_x: 2.5
   weight_kinematics_forward_drive: 100000
   max_vel_theta: 3.8
   acc_lim_x: 2.5
   acc_lim_theta: 3.2
   min_turning_radius: 0.6446
   wheelbase: 0.287
   cmd_angle_instead_rotvel: false
   min_obstacle_dist: 0.4
   xy_goal_tolerance: 0.1
   yaw_goal_tolerance: 0.1
   robot_width: 0.5
   robot_length: 0.5
   footprint: [[-0.25, -0.25], [0.25, -0.25], [0.25, 0.25], [-0.25, 0.25]]
   global_plan_viapoint_sep: -1.0  # Avoids reliance on global plan
   enable_homotopy_class_planning: false  # Prevents path switching
   # Add any other relevant parameters
